### ISSUE TITLE
Magnetic model question

### ISSUE THREAD

**Issue by arenas7307979** [pcdangio/ros-calibration_imu#8]
Hi, thank you very much for sharing
I have some questions, hope you can help

1. mag calibration result: 4x4 matrix that means like  
     mag_calibrated  = R*scale[3x3] * input_mag + bias[3x1]
2. input mag unit is T, not uT or nT
3. NOAA's World Magnetic Model (uT),  
    Do I have to calibrate it every time I change the scene? 
    or I just only need to  calibrate bias
    It affects the shape and position of the target sphere, but why some calibration methods do not use this input
4. At present, I am trying to compare the calibrated value of the magnetometer device and mobile phone magnetometer [calibrated by Google Maps]. When I was indoors, I did not have the exact true field strength value. What should I do to make a closer mag  value between two devices  (I've gone convert  to Mag_Ned coordinate to compare them in some way that eliminates the difference between attitude and position)

**Comment by pcdangio** [comment]
1. The 4x4 calibration matrix result is a homogeneous transformation matrix that performs rotation, translation, and scale (in that order) to adjust uncalibrated data.
2. The output calibration matrix does expect the uncalibrated magneto data to be in T, which is the ROS standard
3. You only have to do the calibration once. The local magnetic field strength is used once initially to determine how far off the scale error is for the magnetometer. Once the scale error is removed during calibration, you can expect that the calibration will remain accurate no matter where you are in the world (as long as you don't make any modifications to the platform that change hard/soft iron disturbances). Most calibration methods don't use this step because most magnetometer measurements are just normalized into a unit vector where the angles are used. By using this calibration method, the field is properly scaled so you can use actual magnetic field strength measurements for whatever you'd like (e.g. detecting the presence of a nearby magnetic field that may be interfering with your measurement of the earth's field, you can look at your total magnetic field strength and if it doesn't match what is expected at your lat/long/alt according to the world model).
4. You should always perform the calibration outdoors and far from any nearby ferrous metals, power lines, etc. That will give you the purest calibration. If you calibrate indoors, there are all kinds of metals and magnetics and what not inside the building that will interfere with the earth's magnetic field. This will result in incorrect calibrations no matter where you are. Also, the magnetometers in mobile phones are horribly inaccurate, they shouldn't be used as a standard for comparison against, even when calibrated :) Your best bet is to line up your magnetometer with geometric landmarks (cheap and semi effective), or compare with survey-grade equipment.

Hope all that helps!
