### ISSUE TITLE
accelerometer model and algorithm to do calibration

### ISSUE THREAD

**Issue by fboris** [pcdangio/ros-calibration_imu#9]
Hi @pcdangio, Thanks for your great tool!
I have one question: what is model of accelerometer and algorithm(maybe some paper or reference)?

**Comment by pcdangio** [comment]
No problem! Its an amalgamation from multiple papers and standard industry practices. I can do my best to summarize here:

For MEMs based accelerometers, there are alignment, offset, and scaling inaccuracies that come as a result of the manufacturing process. The calibration algorithm/routine basically maps out a 3D ellipsoid captured from the 6 gravity measurement points described in the README. If you were to look at this 3D ellipsoid, you'd see it's not centered at zero (bias), the major/minor axes are all different lengths and not 2*g (scale), and the ellipsoid is rotated such that the major/minor axes are not aligned with the x/y/z axis of the accelerometer (alignment). The algorithm uses an iterative optimization algorithm to find the appropriate 4x4 homogeneous transformation to center the ellipsoid (get rid of bias), rotate it (to fix alignment), and scale it to a sphere with radius = known local gravity strength (fixes scale on all 3 axes). This homogeneous transformation matrix becomes your calibration matrix that you multiply with all of your measurements to calibrate them.

For magnetometers, you have to deal with both "hard iron" and "soft iron" local, static disturbances to the magnetic field. "Hard iron" disturbances are basically caused by magnets near your magnetometer, which are typically found in circuit boards on your platform (for example ferrite beads/chokes on power conditioning circuits). Hard iron disturbances create bias/offsets in your magnetometer readings. "Soft iron" disturbances are caused by ferrous metals (basically anything with iron in it), which weaken magnetic fields that pass through it before they get to your magnetometer. Soft iron disturbances create both scale and alignment issues. Keep in mind, we can only calibrate out "static" disturbances, e.g. hard/soft iron disturbances that do not change on your platform over time. You can't easily calibrate out dynamic electro-magnetic fields from things like electric motors or high-current wires. But anyways, the magnetometer calibration algorithm works similarly to the accelerometer algorithm. You rotate your platform in many circles within earth's magnetic field. The algorithm collects these points and forms them into a 3D ellipsoid, which has bias/offset (hard iron), and alignment/scale problems (soft iron). The same iterative optimization algorithm is used to find the homogeneous transformation matrix to turn the 3D ellipsoid into a sphere that is centered at zero, aligned with the principal axes, and scaled to the expected local magnetic field strength.

Hopefully that helps!
